# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install NPM Dependencies
    - run: npm install
      working-directory: ./wp-content/themes/d-wedding/
      
    - run: npm run prod
      working-directory: ./wp-content/themes/d-wedding/
      
    - uses: burnett01/rsync-deployments@4.0
      name: Snc Content
      with:
        switches: -avzr --exclude="/themes/*"  --include="./wp-content/uploads/*"  --filter=""
        path: ./wp-content/
        remote_path: /var/www/html/wp-content/
        remote_host: 147.182.253.137
        remote_port: 22
        remote_user: deploy
        remote_key: ${{ secrets.DEPLOY_KEY }}
    
    - uses: burnett01/rsync-deployments@4.0
      name: theme sync
      with:
        switches: -avzr --delete --exclude="./wp-admin/*" --exclude="./wp-includes/*"  --include="./wp-content/themes/d-wedding/*" --include="./wp-content/plugins/*"  --filter=""
        path: ./wp-content/themes/bittrex/  
        remote_path: /var/www/html/wp-content/themes/d-wedding/
        remote_host: 147.182.253.137
        remote_port: 22
        remote_user: deploy
        remote_key: ${{ secrets.DEPLOY_KEY }}  
